

import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParseException;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Teknosa
 */
public class VTArayuz extends javax.swing.JFrame {

    /**
     * Creates new form VTArayuz
     */
    public VTArayuz() {
        initComponents();
        listele();
    }
    public void temizle(){
    txtAd.setText("");
    txtSoyad.setText("");
    txtNumara.setText("");
    jcCinsiyet.setSelectedIndex(0);
    jCStaj.setSelected(false);
    
    }
    public void listele() {
    MyConnector connection = new MyConnector();
    Connection conn = connection.getConnector();

    DefaultTableModel dtm = (DefaultTableModel) tblKayit.getModel();
    
    // Önce tabloyu temizleyelim, yoksa tekrar tekrar veri eklenir
    dtm.setRowCount(0);

    try {
        Statement statement = conn.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM durum");

        while (rs.next()) {
            String ogrenciNo = rs.getString("ogrenci_No").trim(); 
            String ad = rs.getString("ogrenci_Ad");
            String soyad = rs.getString("ogrenci_soyad");
            String dogumTarihi = rs.getString("Dogum_tarihi");
            String stajDurumu = rs.getString("stajDurumu");

            // Cinsiyet sütununu al ve kontrol et
            String cinsiyetStr = rs.getString("cinsiyet").trim(); 
            String cinsiyet;

            if (cinsiyetStr.equals("0")) {
                cinsiyet = "Erkek";
            } else if (cinsiyetStr.equals("1")) {
                cinsiyet = "Kadýn";
            } else {
                cinsiyet = "Bilinmiyor"; // Beklenmeyen bir deðer varsa
            }

            // Veriyi tabloya ekle
            dtm.addRow(new String[]{ogrenciNo, ad, soyad, cinsiyet, dogumTarihi, stajDurumu});
        }

    } catch (SQLException sqlExp) {
        JOptionPane.showMessageDialog(rootPane, "Kayýtlar getirilemedi");
        sqlExp.printStackTrace(); // Hata detaylarýný görmek için
    } finally {
        connection.closeConnector();
    }
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumara = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        BTNkaydet = new javax.swing.JButton();
        BTNtemizle = new javax.swing.JButton();
        BTNguncelle = new javax.swing.JButton();
        jcCinsiyet = new javax.swing.JComboBox<>();
        spnDtarih = new javax.swing.JSpinner();
        jCStaj = new javax.swing.JCheckBox();
        btnsil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKayit = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Öðrenci Numarasý");

        jLabel2.setText("Öðrenci Ad");

        jLabel3.setText("Öðrenci Soyad");

        jLabel4.setText("Cinsiyet");

        jLabel5.setText("Tarihi");

        jLabel6.setText("Staj Durumu");

        BTNkaydet.setText("Kayýt Ekle");
        BTNkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNkaydetActionPerformed(evt);
            }
        });

        BTNtemizle.setText("Temizle");
        BTNtemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtemizleActionPerformed(evt);
            }
        });

        BTNguncelle.setText("Güncelle");
        BTNguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguncelleActionPerformed(evt);
            }
        });

        jcCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadýn" }));

        spnDtarih.setModel(new javax.swing.SpinnerDateModel());
        spnDtarih.setEditor(new javax.swing.JSpinner.DateEditor(spnDtarih, "dd/MM/yyyy"));

        jCStaj.setText("Tamamladý");

        btnsil.setText("sil");
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        tblKayit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numara", "Ad", "Soyad", "Cinsiyet", "Tarih", "Staj Durumu"
            }
        ));
        tblKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKayitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKayit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoyad)
                    .addComponent(txtAd)
                    .addComponent(txtNumara)
                    .addComponent(jcCinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnDtarih, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jCStaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNkaydet)
                        .addGap(49, 49, 49)
                        .addComponent(BTNtemizle)
                        .addGap(49, 49, 49)
                        .addComponent(btnsil)
                        .addGap(45, 45, 45)
                        .addComponent(BTNguncelle))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNkaydet)
                    .addComponent(BTNtemizle)
                    .addComponent(BTNguncelle)
                    .addComponent(btnsil))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnDtarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCStaj))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNtemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtemizleActionPerformed
     temizle();
        listele();
    }//GEN-LAST:event_BTNtemizleActionPerformed

    private void BTNkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkaydetActionPerformed
       MyConnector connection=new MyConnector();
        Connection conn = connection.getConnector();
        String ogrenci_Ad=txtAd.getText();
        String ogrenci_soyad=txtSoyad.getText();
        String ogrenci_No=txtNumara.getText();
        int cinsiyet=jcCinsiyet.getSelectedIndex();
        DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
        String Dogum_tarihi=dt.format(spnDtarih.getValue());

        int stajDurumu=1;
        if(jCStaj.isSelected()){stajDurumu=1;}else{stajDurumu=0;}
        
        try {
         Statement statement = conn.createStatement();
          statement.executeUpdate("INSERT INTO durum(ogrenci_No,ogrenci_Ad,ogrenci_soyad,cinsiyet,Dogum_tarihi,stajDurumu) values('"+ogrenci_No+"','"+ogrenci_Ad+"','"+ogrenci_soyad+"',"+cinsiyet+",'"+Dogum_tarihi+"',"+stajDurumu+")");
          JOptionPane.showMessageDialog(rootPane,"kayýt gerçekleþti");
          temizle();
} catch (SQLException e) {
    e.printStackTrace();
    
    JOptionPane.showMessageDialog(rootPane, "Kayýt gerçekleþtirilemedi");
}finally{
        connection.closeConnector();
        }


        listele();
    }//GEN-LAST:event_BTNkaydetActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
           MyConnector connection = new MyConnector();
           Connection conn = connection.getConnector();
   
    String ogrenci_No = txtNumara.getText().trim();
    if (!ogrenci_No.equals("")) {   
        int karar = JOptionPane.showConfirmDialog(VTArayuz.this, "kayýt silinsin mi?", "Kayýt silme", JOptionPane.YES_NO_OPTION);
        if (karar == JOptionPane.YES_OPTION) {
            try {
                Statement statement = conn.createStatement();
                statement.executeUpdate("DELETE FROM durum WHERE ogrenci_No='" + ogrenci_No + "'");
                JOptionPane.showMessageDialog(VTArayuz.this, "Kayýt Silindi..");
                temizle();
            } catch (SQLException sqlEXP) {
                JOptionPane.showMessageDialog(VTArayuz.this, "Kayýt silinemedi");
                sqlEXP.printStackTrace();
            } finally {
                connection.closeConnector();
            }
        }    
    } else {
        JOptionPane.showMessageDialog(VTArayuz.this, "Silmek istediðiniz numarayý yazýnýz");
    }
        
        listele();
    }//GEN-LAST:event_btnsilActionPerformed

    private void BTNguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguncelleActionPerformed
         MyConnector connection = new MyConnector();
           Connection conn = connection.getConnector();
   
    String ogrenci_No = txtNumara.getText().trim();
    if (!ogrenci_No.equals("")) {   
        int karar = JOptionPane.showConfirmDialog(VTArayuz.this, "kayýt güncellensin mi mi?", "Kayýt güncelleme", JOptionPane.YES_NO_OPTION);
        if (karar == JOptionPane.YES_OPTION) {
            try {
                 String ogrenci_Ad=txtAd.getText();
                 String ogrenci_soyad=txtSoyad.getText();
                 int cinsiyet=jcCinsiyet.getSelectedIndex();
                  DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
                   String Dogum_tarihi=dt.format(spnDtarih.getValue());
                   int stajDurumu=1;
                   if(jCStaj.isSelected()){stajDurumu=1;}else{stajDurumu=0;}
                Statement statement = conn.createStatement();
                statement.executeUpdate("UPDATE durum SET ogrenci_Ad='"+ogrenci_Ad+"',ogrenci_soyad='"+ogrenci_soyad+"',cinsiyet="+cinsiyet+",Dogum_tarihi='"+Dogum_tarihi+"',stajDurumu="+stajDurumu+" WHERE (ogrenci_No='"+ogrenci_No+"')");
                JOptionPane.showMessageDialog(VTArayuz.this, "Kayýt Güncellendi..");
                temizle();
            } catch (SQLException sqlEXP) {
                JOptionPane.showMessageDialog(VTArayuz.this, "Kayýt Güncellendi.");
                sqlEXP.printStackTrace();
            } finally {
                connection.closeConnector();
            }
        }    
    } else {
        JOptionPane.showMessageDialog(VTArayuz.this, "Güncellemek  istediðiniz numarayý yazýnýz");
    }
listele();
    }//GEN-LAST:event_BTNguncelleActionPerformed

    private void tblKayitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKayitMouseClicked
        if (tblKayit.getSelectedRow()!=-1) {
            String ogrenci_No=tblKayit.getValueAt(tblKayit.getSelectedRow(),0).toString();
            MyConnector connection = new MyConnector();
           Connection conn = connection.getConnector();
           
           
            try {
                Statement statement=conn.createStatement();
               
                ResultSet rs = statement.executeQuery("SELECT * FROM durum WHERE ogrenci_No='" + ogrenci_No + "'");
               rs.next();
               txtNumara.setText(rs.getString("ogrenci_No"));
               txtAd.setText(rs.getString("ogrenci_Ad"));
               txtSoyad.setText(rs.getString("ogrenci_soyad"));
               jcCinsiyet.setSelectedIndex(rs.getInt("cinsiyet"));
              String tarihStr = rs.getString("dogum_tarihi");
                if (tarihStr != null && !tarihStr.isEmpty()) {
                    try {
                        // Veritabanýndaki formatý belirleyerek doðru þekilde parse edelim
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        Date dogumTarihi = sdf.parse(tarihStr);
                        spnDtarih.setValue(dogumTarihi);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(rootPane, "Tarih formatý hatalý: " + tarihStr);
                        e.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Doðum tarihi verisi boþ!");
                }
               
                if (rs.getInt("stajDurumu")==1) {
                    jCStaj.setSelected(true);
                    
                }else{
                
                jCStaj.setSelected(false);
                }
               
                
            } catch (SQLException sqlExp) {
                    JOptionPane.showMessageDialog(rootPane,"Kayýt Getirilme Baþarýlý");
                    sqlExp.printStackTrace();
            }finally{
            connection.closeConnector();
            }
           
           
           listele();
        }
        
        
        
        
        
    }//GEN-LAST:event_tblKayitMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTArayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNguncelle;
    private javax.swing.JButton BTNkaydet;
    private javax.swing.JButton BTNtemizle;
    private javax.swing.JButton btnsil;
    private javax.swing.JCheckBox jCStaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCinsiyet;
    private javax.swing.JSpinner spnDtarih;
    private javax.swing.JTable tblKayit;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtNumara;
    private javax.swing.JTextField txtSoyad;
    // End of variables declaration//GEN-END:variables
}
